### ISSUE TITLE
Поправил конспект.

### ISSUE THREAD

**Issue by sellerbto** [kozlov-ma/Conspect#2]
Что сделано?

Добавлена информация:
- про многочлены нулевой степени
- про обратные многочлены
- примеры разные
- некоторые примеры

Исправлены ошибки:
- в определении делимости многочленов

[Многочлены.md](https://github.com/kozlov-ma/Conspect/files/10790697/default.md)

**Comment by kozlov-ma** [comment]
лучше бы пулл реквест конечно

**Comment by kozlov-ma** [comment]
лучше бы пулл реквест конечно
